/**
 * `cfcf completion <shell>` -- emit a static shell completion script
 * derived from the commander.js command tree.
 *
 * Approach: walk `program.commands` recursively at script-emit time and
 * inline the verb tree into a bash/zsh function. The emitted script is
 * pure shell -- no runtime callbacks to `cfcf`, so completion is fast
 * (no Bun cold-start per tab press) and doesn't break if `cfcf` is
 * missing from $PATH temporarily.
 *
 * Usage:
 *   cfcf completion bash > ~/.cfcf-completion.bash
 *   echo 'source ~/.cfcf-completion.bash' >> ~/.bashrc
 *
 * Or via the install helper:
 *   cfcf completion install            # prints shell-specific instructions
 *
 * Same shape as `gh completion`, `kubectl completion`, etc. -- we don't
 * auto-edit user rc files (trust principle).
 *
 * Plan item 5.8 follow-up; landed alongside the verb-normalisation rename
 * because completion is meaningful only after the verb tree stabilises.
 */

import type { Command } from "commander";
import { writeFileSync, mkdirSync, existsSync, readFileSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

interface NodeInfo {
  /** Command name (last token, e.g. "search", "ingest", "docs"). */
  name: string;
  /** Long flags collected from `.option()` and `.requiredOption()`. */
  flags: string[];
  /** Sub-nodes for namespaces. Empty for leaf verbs. */
  children: NodeInfo[];
}

/**
 * Walk a commander Command + its descendants into a serialisable tree
 * the shell scripts can consume. Skips the autogenerated `help` command
 * (commander always adds one; users don't need to tab-complete it).
 */
export function walkCommands(cmd: Command): NodeInfo {
  const flags: string[] = [];
  // commander stores options on `_optionValues` plus `options`; the public
  // accessor is `cmd.options`. Each option has `.long` (the --foo form)
  // and `.short` (-f). We surface long flags only -- short flags don't
  // benefit from tab completion (they're already short).
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const opts = (cmd as any).options ?? [];
  for (const opt of opts) {
    if (typeof opt.long === "string" && opt.long.startsWith("--")) {
      flags.push(opt.long);
    }
  }
  // `--help` is added by commander automatically on every command but
  // doesn't appear in `cmd.options`. Surface it explicitly so users can
  // tab-complete it.
  flags.push("--help");

  const children: NodeInfo[] = [];
  for (const sub of cmd.commands) {
    if (sub.name() === "help") continue; // commander's autogenerated help command
    children.push(walkCommands(sub));
  }

  return {
    name: cmd.name(),
    flags: [...new Set(flags)].sort(),
    children,
  };
}

/**
 * Render a bash completion script that handles the cfcf verb tree.
 *
 * Strategy: COMP_CWORD points at the position the cursor is at;
 * COMP_WORDS[1..i-1] is the chain of subcommands before the cursor.
 * We descend the embedded tree by following those words, then emit the
 * candidate set (subcommand names + long flags) as completion options.
 */
export function renderBashCompletion(root: NodeInfo): string {
  const tree = JSON.stringify(serialiseForShell(root));
  return `# bash completion for cfcf -- generated by \`cfcf completion bash\`
# Source this file from your ~/.bashrc:
#   source ~/.cfcf-completion.bash
#
# The tree below is inlined at generation time so completion stays fast
# (no \`cfcf\` invocation per tab press). Re-generate after upgrading cfcf.

_cfcf_complete() {
  local cur prev words cword
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"

  # Embedded command tree. JSON-shaped: { children: [...], flags: [...] } per node.
  local tree='${tree}'

  # Walk the tree using jq-equivalent shell parsing. We do this in pure
  # bash to avoid a hard \`jq\` dep. The tree shape is shallow (4 levels
  # max: clio docs ingest --document-id), so we hand-walk it.
  local -a path=()
  local i=1
  while [ "$i" -lt "$COMP_CWORD" ]; do
    local w="\${COMP_WORDS[$i]}"
    case "$w" in
      -*) ;;  # skip flags when descending
      *) path+=("$w") ;;
    esac
    i=$((i+1))
  done

  # Resolve candidates by feeding tree + path into a small shell helper.
  local candidates
  candidates="$(_cfcf_candidates_at "$tree" "\${path[@]}")"
  COMPREPLY=( $(compgen -W "$candidates" -- "$cur") )
}

# Helper: prints space-separated candidates (subcommand names + long flags)
# for the given path through the tree.
_cfcf_candidates_at() {
  local tree="$1"; shift
  # Use python (preferred, ships with macOS + most Linux) or fall back
  # to a no-op. We avoid jq because installing jq for completion is a
  # poor-UX requirement.
  if command -v python3 >/dev/null 2>&1; then
    python3 - <<EOF "$tree" "$@"
import json, sys
tree = json.loads(sys.argv[1])
node = tree
for token in sys.argv[2:]:
    found = None
    for child in node.get("children", []):
        if child["name"] == token:
            found = child
            break
    if found is None:
        # Unknown token -- still useful to show all current children + flags.
        break
    node = found
names = [c["name"] for c in node.get("children", [])]
flags = node.get("flags", [])
print(" ".join(names + flags))
EOF
  fi
}

complete -F _cfcf_complete cfcf
`;
}

/**
 * Render a zsh completion script.
 *
 * Structure follows the standard zsh autoload-via-fpath convention:
 *   - First line is `#compdef cfcf` -- this is what zsh reads to bind
 *     the file as the completion function for the `cfcf` command. The
 *     file MUST be named `_cfcf` and live on `$fpath`.
 *   - The file body IS the completion code (no `_cfcf() { ... }`
 *     wrapper). This is the convention every standard zsh completion
 *     follows: when zsh autoloads the file, it executes the body in
 *     completion context. Wrapping the body in a same-named function
 *     and adding `compdef _cfcf cfcf` at the bottom is for the
 *     **eval-on-source** path, which most users don't use.
 *
 * Variable naming: avoids `path`, which is zsh's special tied-to-$PATH
 * array. Using `local path` makes a local but the tying behaviour can
 * still confuse downstream code. Use `cfcf_path` instead.
 *
 * Verified end-to-end on macOS zsh 5.9 via a fresh subshell + fpath
 * + compinit dance. See `completion.test.ts`.
 */
export function renderZshCompletion(root: NodeInfo): string {
  const tree = JSON.stringify(serialiseForShell(root));
  return `#compdef cfcf
# zsh completion for cfcf -- generated by \`cfcf completion zsh\`
# Place this file in a directory on your $fpath, named exactly _cfcf:
#   mkdir -p ~/.zsh/completions
#   cfcf completion zsh > ~/.zsh/completions/_cfcf
#   # then add this to your ~/.zshrc (if not already present):
#   #   fpath=(~/.zsh/completions $fpath)
#   #   autoload -U compinit && compinit
#   # then: rm -f ~/.zcompdump*; exec zsh

# Embedded command tree -- regenerate via \`cfcf completion zsh\`
# after upgrading cfcf to pick up new verbs. (scripts/install.sh +
# \`cfcf self-update\` + the bun-install postinstall hook do this for you.)
local _cfcf_tree='${tree}'
local -a _cfcf_candidates _cfcf_path

# Collect path tokens before the cursor (skip flags). \`words\` is zsh's
# array of the current command line; CURRENT is 1-indexed at the cursor.
{
  local i
  for ((i=2; i < CURRENT; i++)); do
    case "\${words[$i]}" in
      -*) ;;
      *) _cfcf_path+=("\${words[$i]}") ;;
    esac
  done
}

if (( $+commands[python3] )); then
  _cfcf_candidates=( \${(f)"$(python3 -c '
import json, sys
tree = json.loads(sys.argv[1])
node = tree
for token in sys.argv[2:]:
    found = None
    for child in node.get("children", []):
        if child["name"] == token:
            found = child
            break
    if found is None:
        break
    node = found
names = [c["name"] for c in node.get("children", [])]
flags = node.get("flags", [])
print("\\n".join(names + flags))
' "$_cfcf_tree" "\${_cfcf_path[@]}")"} )
  compadd -a _cfcf_candidates
fi
`;
}

/**
 * Trim the tree to the fields the shell scripts actually need.
 * (Currently identical to NodeInfo; kept as a separate function so we
 * can drop richer fields later without breaking the shell scripts.)
 */
function serialiseForShell(node: NodeInfo): NodeInfo {
  return {
    name: node.name,
    flags: node.flags,
    children: node.children.map(serialiseForShell),
  };
}

/**
 * Detect the user's shell from $SHELL. Returns "bash" | "zsh" | null.
 * Used by `cfcf completion install` to print the right instructions.
 */
export function detectShell(): "bash" | "zsh" | null {
  const shell = process.env.SHELL ?? "";
  if (shell.endsWith("/zsh")) return "zsh";
  if (shell.endsWith("/bash")) return "bash";
  return null;
}

/**
 * Canonical paths where regenerated completion files live. Same paths
 * `cfcf completion install` recommends. Stable so install.sh +
 * `cfcf self-update` can both regenerate-in-place without reading user
 * preferences.
 *
 * `process.env.HOME ?? os.homedir()` so tests can override the path
 * via `HOME`. (Node's `homedir()` reads userInfo at process start and
 * doesn't repick when env changes.)
 */
function userHome(): string {
  return process.env.HOME ?? homedir();
}
export function bashCompletionPath(): string {
  return join(userHome(), ".cfcf-completion.bash");
}
export function zshCompletionPath(): string {
  return join(userHome(), ".zsh", "completions", "_cfcf");
}

export interface RegenerateResult {
  shell: "bash" | "zsh" | "both" | "none";
  /** Files we actually wrote this run. */
  written: string[];
  /** True iff at least one of the written files didn't exist before. */
  freshInstall: boolean;
}

/**
 * Sentinel-marked block we append to the user's shell rc file. Same
 * convention as the `<!-- cfcf:begin --> ... <!-- cfcf:end -->` markers
 * in CLAUDE.md / AGENTS.md: cfcf only modifies content between these
 * markers; the rest of the user's rc file is untouched. The block can
 * be safely deleted by the user to opt out.
 */
const RC_BLOCK_BEGIN = "# >>> cfcf shell completion (managed by `cfcf completion install`) >>>";
const RC_BLOCK_END   = "# <<< cfcf shell completion <<<";

function rcBlockBody(shell: "bash" | "zsh"): string {
  if (shell === "zsh") {
    return [
      RC_BLOCK_BEGIN,
      "# Auto-added on cfcf install/upgrade. Delete this block (begin to end markers)",
      "# to opt out; cfcf only modifies content between the >>> and <<< sentinels.",
      "fpath=(~/.zsh/completions $fpath)",
      "autoload -U compinit && compinit",
      RC_BLOCK_END,
    ].join("\n");
  }
  // bash
  return [
    RC_BLOCK_BEGIN,
    "# Auto-added on cfcf install/upgrade. Delete this block (begin to end markers)",
    "# to opt out; cfcf only modifies content between the >>> and <<< sentinels.",
    '[ -s "$HOME/.cfcf-completion.bash" ] && source "$HOME/.cfcf-completion.bash"',
    RC_BLOCK_END,
  ].join("\n");
}

function rcFilePath(shell: "bash" | "zsh"): string {
  return shell === "zsh"
    ? join(userHome(), ".zshrc")
    : join(userHome(), ".bashrc");
}

/**
 * Pattern indicating the user already wired completion up by hand. We
 * detect this and skip our auto-edit so we don't fight their setup.
 *
 * For zsh: any `fpath` line that includes `.zsh/completions` or any
 * `source` line that points at our completion file.
 * For bash: any `source` line referencing our `.cfcf-completion.bash`.
 *
 * Conservative: we'd rather skip when ambiguous than duplicate.
 */
function rcHasManualSetup(shell: "bash" | "zsh", rcContent: string): boolean {
  if (shell === "zsh") {
    if (/^\s*fpath=.*\.zsh\/completions/m.test(rcContent)) return true;
    if (/source\s+.*\.zsh\/completions\/_cfcf/.test(rcContent)) return true;
    return false;
  }
  return /source\s+.*\.cfcf-completion\.bash/.test(rcContent);
}

export interface InstallRcResult {
  /** Always set when an action was attempted; null when shell is unsupported. */
  rcFile: string | null;
  /**
   * What we did:
   *   - `added`     : sentinel block didn't exist; we appended it.
   *   - `updated`   : sentinel block existed; we replaced it (verbatim
   *                   or with refreshed contents).
   *   - `unchanged` : sentinel block existed AND matched the desired
   *                   content; nothing written.
   *   - `skipped-manual` : the user has an existing manual setup
   *                   (e.g. their own `fpath=(...)` line). We don't
   *                   want to fight their config, so we leave it
   *                   alone.
   *   - `skipped-unsupported` : $SHELL isn't bash or zsh. No-op.
   */
  action: "added" | "updated" | "unchanged" | "skipped-manual" | "skipped-unsupported";
}

/**
 * Append (or update) the cfcf completion block in the user's shell rc
 * file. Idempotent: re-running this on an already-installed setup is a
 * no-op (`unchanged`). Trust principle: cfcf only modifies content
 * between the sentinel markers; the rest of the user's rc file is
 * untouched.
 *
 * Detects pre-existing manual setup and skips with `skipped-manual` so
 * users who hand-managed their fpath/source line don't get duplicated.
 *
 * Best-effort: file-write errors are returned via the result, never
 * thrown. The caller decides how loud to be.
 */
export function installShellRcEntry(): InstallRcResult {
  const shell = detectShell();
  if (shell === null) return { rcFile: null, action: "skipped-unsupported" };

  const rcFile = rcFilePath(shell);
  const desiredBlock = rcBlockBody(shell);

  let existing = "";
  if (existsSync(rcFile)) existing = readFileSync(rcFile, "utf-8");

  // 1. Manual-setup detection comes first: if the user wired things up
  //    themselves, leave their rc alone.
  if (existing && rcHasManualSetup(shell, existing) && !existing.includes(RC_BLOCK_BEGIN)) {
    return { rcFile, action: "skipped-manual" };
  }

  // 2. Sentinel block already present? Replace its contents (idempotent
  //    refresh, in case future cfcf versions tweak the block).
  if (existing.includes(RC_BLOCK_BEGIN) && existing.includes(RC_BLOCK_END)) {
    const startIdx = existing.indexOf(RC_BLOCK_BEGIN);
    const endIdx = existing.indexOf(RC_BLOCK_END) + RC_BLOCK_END.length;
    const next = existing.slice(0, startIdx) + desiredBlock + existing.slice(endIdx);
    if (next === existing) {
      return { rcFile, action: "unchanged" };
    }
    writeFileSync(rcFile, next, { mode: 0o644 });
    return { rcFile, action: "updated" };
  }

  // 3. Append to the end of the rc file (creating it if missing).
  const sep = existing === "" ? "" : existing.endsWith("\n") ? "\n" : "\n\n";
  writeFileSync(rcFile, existing + sep + desiredBlock + "\n", { mode: 0o644 });
  return { rcFile, action: "added" };
}

/**
 * Remove the cfcf-managed sentinel block from the user's rc file (if
 * present) AND delete the completion file we wrote. Symmetrical with
 * `installShellRcEntry` + `regenerateShellCompletion`. Used by
 * `cfcf completion uninstall`. Best-effort: missing files are no-ops.
 */
export function uninstallShellCompletion(): {
  shell: "bash" | "zsh" | "none";
  removedRcBlock: boolean;
  removedFile: boolean;
  rcFile: string | null;
  completionFile: string | null;
} {
  const shell = detectShell();
  if (shell === null) {
    return { shell: "none", removedRcBlock: false, removedFile: false, rcFile: null, completionFile: null };
  }

  const rcFile = rcFilePath(shell);
  const completionFile = shell === "zsh" ? zshCompletionPath() : bashCompletionPath();

  let removedRcBlock = false;
  if (existsSync(rcFile)) {
    const content = readFileSync(rcFile, "utf-8");
    if (content.includes(RC_BLOCK_BEGIN) && content.includes(RC_BLOCK_END)) {
      const startIdx = content.indexOf(RC_BLOCK_BEGIN);
      const endIdx = content.indexOf(RC_BLOCK_END) + RC_BLOCK_END.length;
      // Trim a trailing newline introduced by `installShellRcEntry`'s append.
      let stripped = content.slice(0, startIdx) + content.slice(endIdx);
      if (stripped.startsWith("\n\n")) stripped = stripped.slice(1); // collapse double-blank we may have inserted
      if (stripped.endsWith("\n\n")) stripped = stripped.slice(0, -1);
      writeFileSync(rcFile, stripped, { mode: 0o644 });
      removedRcBlock = true;
    }
  }

  let removedFile = false;
  if (existsSync(completionFile)) {
    unlinkSync(completionFile);
    removedFile = true;
  }

  return { shell, removedRcBlock, removedFile, rcFile, completionFile };
}

/**
 * Regenerate the shell completion file(s) for the user's shell.
 * Idempotent: writing over an existing file leaves the user's
 * `source` line in their rc untouched. The first run (file didn't
 * exist) is the only time we should print the source-this-line
 * instruction; subsequent runs (post-upgrade) are silent.
 *
 * Strategy:
 *   - If $SHELL is bash → write ~/.cfcf-completion.bash
 *   - If $SHELL is zsh  → write ~/.zsh/completions/_cfcf
 *   - If neither (CI, sh, fish, …) → no-op (returns shell:"none")
 *
 * Used by:
 *   - scripts/install.sh (immediately after the bun-install step)
 *   - packages/cli/src/commands/self-update.ts (post-upgrade)
 *
 * Best-effort: errors are caught + reported but never fail the
 * outer install/upgrade flow. Completion is a quality-of-life
 * feature, not a critical path.
 */
export function regenerateShellCompletion(program: Command): RegenerateResult {
  const shell = detectShell();
  if (shell === null) return { shell: "none", written: [], freshInstall: false };

  const tree = walkCommands(program);
  const written: string[] = [];
  let freshInstall = false;

  if (shell === "bash") {
    const path = bashCompletionPath();
    if (!existsSync(path)) freshInstall = true;
    writeFileSync(path, renderBashCompletion(tree), { mode: 0o644 });
    written.push(path);
  } else if (shell === "zsh") {
    const path = zshCompletionPath();
    // The directory must exist before the user can `fpath`-add it.
    mkdirSync(join(userHome(), ".zsh", "completions"), { recursive: true });
    if (!existsSync(path)) freshInstall = true;
    writeFileSync(path, renderZshCompletion(tree), { mode: 0o644 });
    written.push(path);
  }

  return { shell, written, freshInstall };
}

export function registerCompletionCommand(program: Command): void {
  // Top-level `cfcf completion` since shell completion is a cfcf-level
  // concern, not a Clio one. Lives alongside `init`, `status`, `doctor`.
  const completionCmd = program
    .command("completion")
    .description("Emit shell completion scripts (bash, zsh) for the cfcf CLI");

  completionCmd
    .command("bash")
    .description("Emit a bash completion script (redirect to a file + source it)")
    .action(() => {
      // We need access to the parent program to walk its tree. Commander
      // exposes the parent via `.parent`.
      const root = program;
      const tree = walkCommands(root);
      process.stdout.write(renderBashCompletion(tree));
    });

  completionCmd
    .command("zsh")
    .description("Emit a zsh completion script (place on your $fpath as _cfcf)")
    .action(() => {
      const root = program;
      const tree = walkCommands(root);
      process.stdout.write(renderZshCompletion(tree));
    });

  completionCmd
    .command("install")
    .description("Install tab completion + auto-add the rc entry (sentinel-marked, easy to remove)")
    .option("--print-only", "Don't write any files; just print the manual setup instructions")
    .option("--no-rc-edit", "Write the completion script but DON'T touch your shell rc file")
    .action((opts: { printOnly?: boolean; rcEdit?: boolean }) => {
      const detected = detectShell();
      if (opts.printOnly || detected === null) {
        printCompletionInstructions(detected);
        return;
      }

      // Step 1: write the completion script. Same paths as before --
      // ~/.cfcf-completion.bash for bash, ~/.zsh/completions/_cfcf for zsh.
      const fileResult = regenerateShellCompletion(program);
      const scriptPath = fileResult.written[0];

      // Step 2: append (or refresh) the cfcf-managed block in ~/.zshrc
      // or ~/.bashrc, unless --no-rc-edit was passed. The block is
      // sentinel-marked: cfcf only touches content between the
      // >>> and <<< markers; the user's rc file is otherwise untouched.
      // The block can be removed by deleting the marked region or by
      // running `cfcf completion uninstall`.
      const rcEdit = opts.rcEdit !== false;  // default true; --no-rc-edit flips
      const rcResult = rcEdit
        ? installShellRcEntry()
        : { rcFile: null, action: "skipped-unsupported" as const };

      console.log(`cfcf shell completion installed for ${detected}.`);
      console.log(`  wrote completion script: ${scriptPath}`);

      if (rcEdit) {
        switch (rcResult.action) {
          case "added":
            console.log(`  added rc entry:           ${rcResult.rcFile}`);
            break;
          case "updated":
            console.log(`  refreshed rc entry:       ${rcResult.rcFile}`);
            break;
          case "unchanged":
            console.log(`  rc entry already current: ${rcResult.rcFile}`);
            break;
          case "skipped-manual":
            console.log(`  rc file: ${rcResult.rcFile} (left alone -- detected an existing manual fpath/source line)`);
            break;
          case "skipped-unsupported":
            // Shouldn't reach here because we early-returned on shell=null.
            break;
        }
      } else {
        console.log("  rc entry skipped (--no-rc-edit). Manual setup:");
        if (detected === "zsh") {
          console.log("    Add to ~/.zshrc: fpath=(~/.zsh/completions $fpath); autoload -U compinit && compinit");
        } else {
          console.log(`    Add to ~/.bashrc: source ${scriptPath}`);
        }
      }

      console.log();
      const needsActivation = rcResult.action === "added" || rcResult.action === "updated" || !rcEdit;
      if (needsActivation) {
        console.log(`Activate now:  exec ${detected}`);
        console.log("(or just open a new terminal)");
        console.log();
      }
      console.log("Tab-complete works on every cfcf verb:");
      console.log("  cfcf <TAB>            → top-level commands");
      console.log("  cfcf clio <TAB>       → docs metadata projects embedder search audit reindex stats");
      console.log("  cfcf clio docs <TAB>  → list ingest get edit delete restore versions");
      console.log();
      console.log("Auto-regenerated on every cfcf install + `cfcf self-update`. Rarely");
      console.log("needs to be re-run. To opt out / remove: `cfcf completion uninstall`.");
    });

  completionCmd
    .command("uninstall")
    .description("Remove cfcf shell completion (rc-file block + completion script)")
    .action(() => {
      const result = uninstallShellCompletion();
      if (result.shell === "none") {
        console.log("Couldn't detect your shell from $SHELL. Nothing to uninstall.");
        return;
      }
      console.log(`cfcf shell completion uninstall for ${result.shell}:`);
      if (result.removedRcBlock) {
        console.log(`  ✓ removed rc block from: ${result.rcFile}`);
      } else {
        console.log(`  - rc block already absent: ${result.rcFile}`);
      }
      if (result.removedFile) {
        console.log(`  ✓ removed completion script: ${result.completionFile}`);
      } else {
        console.log(`  - completion script already absent: ${result.completionFile}`);
      }
      if (result.removedRcBlock || result.removedFile) {
        console.log();
        console.log(`Run \`exec ${result.shell}\` (or open a new terminal) to deactivate.`);
        console.log("Re-install any time with: cfcf completion install");
      }
    });
}

/**
 * Print the manual install instructions (the old `cfcf completion install`
 * behaviour). Used when the user passes `--print-only` or when $SHELL
 * isn't recognised and we can't safely auto-install.
 */
function printCompletionInstructions(detected: "bash" | "zsh" | null): void {
  console.log("cfcf shell completion -- install instructions");
  console.log();
  if (detected === "bash" || detected === null) {
    console.log("Bash:");
    console.log("  cfcf completion bash > ~/.cfcf-completion.bash");
    console.log("  echo 'source ~/.cfcf-completion.bash' >> ~/.bashrc");
    console.log("  # then open a new shell, or: source ~/.bashrc");
    console.log();
  }
  if (detected === "zsh" || detected === null) {
    console.log("Zsh:");
    console.log("  mkdir -p ~/.zsh/completions");
    console.log("  cfcf completion zsh > ~/.zsh/completions/_cfcf");
    console.log("  # add to ~/.zshrc if not already present:");
    console.log("  #   fpath=(~/.zsh/completions $fpath)");
    console.log("  #   autoload -U compinit && compinit");
    console.log();
  }
  if (detected) {
    console.log(`(Detected shell: ${detected}.)`);
  } else {
    console.log("(Couldn't detect your shell from $SHELL; both forms shown.)");
  }
}
