/**
 * Tests for the `cfcf completion <shell>` generator.
 *
 * Approach: build a small commander tree in-memory that mirrors the
 * shapes the real CLI uses (top-level verbs + namespaces + nested
 * subcommands), walk it, and verify the produced tree + scripts.
 */

import { describe, it, expect } from "bun:test";
import { Command } from "commander";
import { walkCommands, renderBashCompletion, renderZshCompletion } from "./completion.js";

function buildSampleProgram(): Command {
  // Mirrors the real cfcf shape on a small scale so the test catches
  // regressions in tree-walking. Three levels deep matches the deepest
  // path in the real CLI (`cfcf clio docs ingest`).
  const program = new Command()
    .name("cfcf")
    .version("1.2.3");

  program
    .command("status")
    .option("--workspace <name>", "scope to one workspace")
    .description("Show overall status");

  // Two-level namespace.
  const workspace = program
    .command("workspace")
    .description("Workspace operations");
  workspace
    .command("list")
    .option("--json", "raw JSON")
    .description("List workspaces");
  workspace
    .command("show <name>")
    .description("Show one workspace");

  // Three-level namespace + nested namespace -- mirrors clio docs ingest.
  const clio = program
    .command("clio")
    .description("Clio memory layer");
  clio
    .command("search <q>")
    .option("--alpha <n>", "blend weight")
    .description("Search Clio");
  const docs = clio
    .command("docs")
    .description("Document operations");
  docs
    .command("get <id>")
    .option("--version-id <uuid>", "archived version")
    .description("Get a document");
  docs
    .command("ingest [file]")
    .option("--title <t>")
    .option("--project <p>")
    .description("Ingest a document");

  return program;
}

describe("walkCommands", () => {
  it("walks a flat program into a single root node with children + flags", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);

    expect(tree.name).toBe("cfcf");
    expect(tree.flags).toContain("--help");
    expect(tree.flags).toContain("--version");

    // Top-level verbs.
    const childNames = tree.children.map((c) => c.name).sort();
    expect(childNames).toEqual(["clio", "status", "workspace"]);
  });

  it("descends into namespaces (clio docs ingest)", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);

    const clio = tree.children.find((c) => c.name === "clio");
    expect(clio).toBeDefined();
    expect(clio!.children.map((c) => c.name).sort()).toEqual(["docs", "search"]);

    const docs = clio!.children.find((c) => c.name === "docs");
    expect(docs!.children.map((c) => c.name).sort()).toEqual(["get", "ingest"]);

    const ingest = docs!.children.find((c) => c.name === "ingest");
    expect(ingest!.flags).toContain("--title");
    expect(ingest!.flags).toContain("--project");
    expect(ingest!.flags).toContain("--help");
  });

  it("filters out commander's autogenerated `help` subcommand", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);
    const allNames = collectNames(tree);
    expect(allNames).not.toContain("help");
  });

  it("each node lists --help even when no .option('--help') was registered", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);
    const allNodes = collectNodes(tree);
    for (const n of allNodes) {
      expect(n.flags).toContain("--help");
    }
  });

  it("flags are deduped + sorted", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);
    const allNodes = collectNodes(tree);
    for (const n of allNodes) {
      const sorted = [...n.flags].sort();
      expect(n.flags).toEqual(sorted);
      expect(new Set(n.flags).size).toBe(n.flags.length);
    }
  });
});

describe("renderBashCompletion", () => {
  it("emits a sourceable bash script with the embedded tree", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);
    const script = renderBashCompletion(tree);

    expect(script).toContain("_cfcf_complete()");
    expect(script).toContain("complete -F _cfcf_complete cfcf");
    // Tree gets inlined as a JSON string. Spot-check that some known
    // verbs survived the round-trip.
    expect(script).toContain('"name":"cfcf"');
    expect(script).toContain('"name":"clio"');
    expect(script).toContain('"name":"docs"');
    expect(script).toContain('"name":"ingest"');
    // Flags too.
    expect(script).toContain("--version-id");
    expect(script).toContain("--alpha");
  });

  it("the embedded JSON tree is parseable", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);
    const script = renderBashCompletion(tree);
    // Pull the JSON literal between single-quotes after `local tree=`.
    const m = script.match(/local tree='(\{.*?\})'/);
    expect(m).not.toBeNull();
    const parsed = JSON.parse(m![1]);
    expect(parsed.name).toBe("cfcf");
    expect(parsed.children.length).toBeGreaterThan(0);
  });
});

describe("renderZshCompletion", () => {
  it("emits a #compdef directive + _cfcf function", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);
    const script = renderZshCompletion(tree);

    expect(script.startsWith("#compdef cfcf")).toBe(true);
    expect(script).toContain("_cfcf()");
    expect(script).toContain("compdef _cfcf cfcf");
  });

  it("the embedded JSON tree is parseable", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);
    const script = renderZshCompletion(tree);
    const m = script.match(/local tree='(\{.*?\})'/);
    expect(m).not.toBeNull();
    const parsed = JSON.parse(m![1]);
    expect(parsed.children.length).toBeGreaterThan(0);
  });
});

// ── helpers ──────────────────────────────────────────────────────────────

function collectNames(node: { name: string; children: { name: string; children: unknown[] }[] }): string[] {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const out = [node.name];
  for (const c of node.children) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    out.push(...collectNames(c as any));
  }
  return out;
}

function collectNodes(node: { flags: string[]; children: unknown[] }): { flags: string[] }[] {
  const out: { flags: string[] }[] = [{ flags: node.flags }];
  for (const c of node.children) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    out.push(...collectNodes(c as any));
  }
  return out;
}
