/**
 * Tests for the `cfcf completion <shell>` generator.
 *
 * Approach: build a small commander tree in-memory that mirrors the
 * shapes the real CLI uses (top-level verbs + namespaces + nested
 * subcommands), walk it, and verify the produced tree + scripts.
 */

import { describe, it, expect, beforeEach, afterEach } from "bun:test";
import { Command } from "commander";
import { mkdtempSync, rmSync, existsSync, readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  walkCommands,
  renderBashCompletion,
  renderZshCompletion,
  regenerateShellCompletion,
  bashCompletionPath,
  zshCompletionPath,
} from "./completion.js";

function buildSampleProgram(): Command {
  // Mirrors the real cfcf shape on a small scale so the test catches
  // regressions in tree-walking. Three levels deep matches the deepest
  // path in the real CLI (`cfcf clio docs ingest`).
  const program = new Command()
    .name("cfcf")
    .version("1.2.3");

  program
    .command("status")
    .option("--workspace <name>", "scope to one workspace")
    .description("Show overall status");

  // Two-level namespace.
  const workspace = program
    .command("workspace")
    .description("Workspace operations");
  workspace
    .command("list")
    .option("--json", "raw JSON")
    .description("List workspaces");
  workspace
    .command("show <name>")
    .description("Show one workspace");

  // Three-level namespace + nested namespace -- mirrors clio docs ingest.
  const clio = program
    .command("clio")
    .description("Clio memory layer");
  clio
    .command("search <q>")
    .option("--alpha <n>", "blend weight")
    .description("Search Clio");
  const docs = clio
    .command("docs")
    .description("Document operations");
  docs
    .command("get <id>")
    .option("--version-id <uuid>", "archived version")
    .description("Get a document");
  docs
    .command("ingest [file]")
    .option("--title <t>")
    .option("--project <p>")
    .description("Ingest a document");

  return program;
}

describe("walkCommands", () => {
  it("walks a flat program into a single root node with children + flags", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);

    expect(tree.name).toBe("cfcf");
    expect(tree.flags).toContain("--help");
    expect(tree.flags).toContain("--version");

    // Top-level verbs.
    const childNames = tree.children.map((c) => c.name).sort();
    expect(childNames).toEqual(["clio", "status", "workspace"]);
  });

  it("descends into namespaces (clio docs ingest)", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);

    const clio = tree.children.find((c) => c.name === "clio");
    expect(clio).toBeDefined();
    expect(clio!.children.map((c) => c.name).sort()).toEqual(["docs", "search"]);

    const docs = clio!.children.find((c) => c.name === "docs");
    expect(docs!.children.map((c) => c.name).sort()).toEqual(["get", "ingest"]);

    const ingest = docs!.children.find((c) => c.name === "ingest");
    expect(ingest!.flags).toContain("--title");
    expect(ingest!.flags).toContain("--project");
    expect(ingest!.flags).toContain("--help");
  });

  it("filters out commander's autogenerated `help` subcommand", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);
    const allNames = collectNames(tree);
    expect(allNames).not.toContain("help");
  });

  it("each node lists --help even when no .option('--help') was registered", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);
    const allNodes = collectNodes(tree);
    for (const n of allNodes) {
      expect(n.flags).toContain("--help");
    }
  });

  it("flags are deduped + sorted", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);
    const allNodes = collectNodes(tree);
    for (const n of allNodes) {
      const sorted = [...n.flags].sort();
      expect(n.flags).toEqual(sorted);
      expect(new Set(n.flags).size).toBe(n.flags.length);
    }
  });
});

describe("renderBashCompletion", () => {
  it("emits a sourceable bash script with the embedded tree", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);
    const script = renderBashCompletion(tree);

    expect(script).toContain("_cfcf_complete()");
    expect(script).toContain("complete -F _cfcf_complete cfcf");
    // Tree gets inlined as a JSON string. Spot-check that some known
    // verbs survived the round-trip.
    expect(script).toContain('"name":"cfcf"');
    expect(script).toContain('"name":"clio"');
    expect(script).toContain('"name":"docs"');
    expect(script).toContain('"name":"ingest"');
    // Flags too.
    expect(script).toContain("--version-id");
    expect(script).toContain("--alpha");
  });

  it("the embedded JSON tree is parseable", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);
    const script = renderBashCompletion(tree);
    // Pull the JSON literal between single-quotes after `local tree=`.
    const m = script.match(/local tree='(\{.*?\})'/);
    expect(m).not.toBeNull();
    const parsed = JSON.parse(m![1]);
    expect(parsed.name).toBe("cfcf");
    expect(parsed.children.length).toBeGreaterThan(0);
  });
});

describe("renderZshCompletion", () => {
  it("emits a #compdef directive + _cfcf function", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);
    const script = renderZshCompletion(tree);

    expect(script.startsWith("#compdef cfcf")).toBe(true);
    expect(script).toContain("_cfcf()");
    expect(script).toContain("compdef _cfcf cfcf");
  });

  it("the embedded JSON tree is parseable", () => {
    const program = buildSampleProgram();
    const tree = walkCommands(program);
    const script = renderZshCompletion(tree);
    const m = script.match(/local tree='(\{.*?\})'/);
    expect(m).not.toBeNull();
    const parsed = JSON.parse(m![1]);
    expect(parsed.children.length).toBeGreaterThan(0);
  });
});

describe("regenerateShellCompletion", () => {
  // Each test gets a temp HOME so we don't write to the real user dir.
  let tempHome: string;
  let savedHome: string | undefined;
  let savedShell: string | undefined;

  beforeEach(() => {
    tempHome = mkdtempSync(join(tmpdir(), "cfcf-completion-test-"));
    savedHome = process.env.HOME;
    savedShell = process.env.SHELL;
    process.env.HOME = tempHome;
  });

  afterEach(() => {
    if (savedHome === undefined) delete process.env.HOME; else process.env.HOME = savedHome;
    if (savedShell === undefined) delete process.env.SHELL; else process.env.SHELL = savedShell;
    try { rmSync(tempHome, { recursive: true, force: true }); } catch { /* ignore */ }
  });

  it("writes ~/.cfcf-completion.bash for bash users; freshInstall=true on first run", () => {
    process.env.SHELL = "/bin/bash";
    const program = buildSampleProgram();

    const result = regenerateShellCompletion(program);

    expect(result.shell).toBe("bash");
    expect(result.freshInstall).toBe(true);
    expect(result.written.length).toBe(1);
    expect(result.written[0]).toBe(bashCompletionPath());
    expect(existsSync(bashCompletionPath())).toBe(true);
    expect(readFileSync(bashCompletionPath(), "utf-8")).toContain("_cfcf_complete()");
  });

  it("writes ~/.zsh/completions/_cfcf for zsh users + creates the dir", () => {
    process.env.SHELL = "/usr/local/bin/zsh";
    const program = buildSampleProgram();

    const result = regenerateShellCompletion(program);

    expect(result.shell).toBe("zsh");
    expect(result.freshInstall).toBe(true);
    expect(result.written[0]).toBe(zshCompletionPath());
    expect(existsSync(zshCompletionPath())).toBe(true);
    expect(readFileSync(zshCompletionPath(), "utf-8")).toContain("#compdef cfcf");
  });

  it("subsequent runs report freshInstall=false (file already existed)", () => {
    process.env.SHELL = "/bin/bash";
    const program = buildSampleProgram();

    regenerateShellCompletion(program);  // first run
    const second = regenerateShellCompletion(program);  // second run

    expect(second.freshInstall).toBe(false);
    expect(second.written[0]).toBe(bashCompletionPath());
    // File still exists + still contains the function (idempotent rewrite).
    expect(existsSync(bashCompletionPath())).toBe(true);
  });

  it("regenerates on every call (picks up new verbs after upgrade)", () => {
    process.env.SHELL = "/bin/bash";
    const oldProgram = buildSampleProgram();
    regenerateShellCompletion(oldProgram);
    const oldContents = readFileSync(bashCompletionPath(), "utf-8");
    expect(oldContents).not.toContain('"name":"newverb"');

    // Simulate an upgrade that adds a verb.
    const newProgram = buildSampleProgram();
    newProgram.command("newverb").description("freshly added verb");
    regenerateShellCompletion(newProgram);

    const newContents = readFileSync(bashCompletionPath(), "utf-8");
    expect(newContents).toContain('"name":"newverb"');
    expect(newContents).not.toEqual(oldContents);
  });

  it("returns shell:'none' (no-op) when $SHELL is fish/sh/empty", () => {
    process.env.SHELL = "/usr/bin/fish";
    const program = buildSampleProgram();

    const result = regenerateShellCompletion(program);

    expect(result.shell).toBe("none");
    expect(result.written.length).toBe(0);
    expect(result.freshInstall).toBe(false);
    // Neither file should have been created.
    expect(existsSync(bashCompletionPath())).toBe(false);
    expect(existsSync(zshCompletionPath())).toBe(false);
  });

  it("doesn't clobber files outside the canonical paths (sanity test)", () => {
    process.env.SHELL = "/bin/bash";
    // Stage a sentinel file in the temp HOME that should NOT be touched.
    const sentinel = join(tempHome, "do-not-touch.txt");
    writeFileSync(sentinel, "sentinel");

    const program = buildSampleProgram();
    regenerateShellCompletion(program);

    expect(readFileSync(sentinel, "utf-8")).toBe("sentinel");
  });

  it("zsh path: doesn't fail when ~/.zsh/completions doesn't pre-exist", () => {
    process.env.SHELL = "/bin/zsh";
    // Confirm the dir doesn't exist; regenerateShellCompletion should mkdir -p it.
    expect(existsSync(join(tempHome, ".zsh", "completions"))).toBe(false);

    const program = buildSampleProgram();
    const result = regenerateShellCompletion(program);

    expect(result.shell).toBe("zsh");
    expect(existsSync(join(tempHome, ".zsh", "completions"))).toBe(true);
    expect(existsSync(zshCompletionPath())).toBe(true);
  });

  it("zsh path: tolerates ~/.zsh/completions pre-existing", () => {
    process.env.SHELL = "/bin/zsh";
    mkdirSync(join(tempHome, ".zsh", "completions"), { recursive: true });
    // Drop a pre-existing _cfcf so we can verify it's overwritten cleanly.
    writeFileSync(zshCompletionPath(), "old contents");

    const program = buildSampleProgram();
    const result = regenerateShellCompletion(program);

    expect(result.shell).toBe("zsh");
    expect(result.freshInstall).toBe(false);  // file existed
    expect(readFileSync(zshCompletionPath(), "utf-8")).not.toBe("old contents");
    expect(readFileSync(zshCompletionPath(), "utf-8")).toContain("#compdef cfcf");
  });
});

// ── helpers ──────────────────────────────────────────────────────────────

function collectNames(node: { name: string; children: { name: string; children: unknown[] }[] }): string[] {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const out = [node.name];
  for (const c of node.children) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    out.push(...collectNames(c as any));
  }
  return out;
}

function collectNodes(node: { flags: string[]; children: unknown[] }): { flags: string[] }[] {
  const out: { flags: string[] }[] = [{ flags: node.flags }];
  for (const c of node.children) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    out.push(...collectNodes(c as any));
  }
  return out;
}
