/**
 * `cfcf completion <shell>` -- emit a static shell completion script
 * derived from the commander.js command tree.
 *
 * Approach: walk `program.commands` recursively at script-emit time and
 * inline the verb tree into a bash/zsh function. The emitted script is
 * pure shell -- no runtime callbacks to `cfcf`, so completion is fast
 * (no Bun cold-start per tab press) and doesn't break if `cfcf` is
 * missing from $PATH temporarily.
 *
 * Usage:
 *   cfcf completion bash > ~/.cfcf-completion.bash
 *   echo 'source ~/.cfcf-completion.bash' >> ~/.bashrc
 *
 * Or via the install helper:
 *   cfcf completion install            # prints shell-specific instructions
 *
 * Same shape as `gh completion`, `kubectl completion`, etc. -- we don't
 * auto-edit user rc files (trust principle).
 *
 * Plan item 5.8 follow-up; landed alongside the verb-normalisation rename
 * because completion is meaningful only after the verb tree stabilises.
 */

import type { Command } from "commander";

interface NodeInfo {
  /** Command name (last token, e.g. "search", "ingest", "docs"). */
  name: string;
  /** Long flags collected from `.option()` and `.requiredOption()`. */
  flags: string[];
  /** Sub-nodes for namespaces. Empty for leaf verbs. */
  children: NodeInfo[];
}

/**
 * Walk a commander Command + its descendants into a serialisable tree
 * the shell scripts can consume. Skips the autogenerated `help` command
 * (commander always adds one; users don't need to tab-complete it).
 */
export function walkCommands(cmd: Command): NodeInfo {
  const flags: string[] = [];
  // commander stores options on `_optionValues` plus `options`; the public
  // accessor is `cmd.options`. Each option has `.long` (the --foo form)
  // and `.short` (-f). We surface long flags only -- short flags don't
  // benefit from tab completion (they're already short).
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const opts = (cmd as any).options ?? [];
  for (const opt of opts) {
    if (typeof opt.long === "string" && opt.long.startsWith("--")) {
      flags.push(opt.long);
    }
  }
  // `--help` is added by commander automatically on every command but
  // doesn't appear in `cmd.options`. Surface it explicitly so users can
  // tab-complete it.
  flags.push("--help");

  const children: NodeInfo[] = [];
  for (const sub of cmd.commands) {
    if (sub.name() === "help") continue; // commander's autogenerated help command
    children.push(walkCommands(sub));
  }

  return {
    name: cmd.name(),
    flags: [...new Set(flags)].sort(),
    children,
  };
}

/**
 * Render a bash completion script that handles the cfcf verb tree.
 *
 * Strategy: COMP_CWORD points at the position the cursor is at;
 * COMP_WORDS[1..i-1] is the chain of subcommands before the cursor.
 * We descend the embedded tree by following those words, then emit the
 * candidate set (subcommand names + long flags) as completion options.
 */
export function renderBashCompletion(root: NodeInfo): string {
  const tree = JSON.stringify(serialiseForShell(root));
  return `# bash completion for cfcf -- generated by \`cfcf completion bash\`
# Source this file from your ~/.bashrc:
#   source ~/.cfcf-completion.bash
#
# The tree below is inlined at generation time so completion stays fast
# (no \`cfcf\` invocation per tab press). Re-generate after upgrading cfcf.

_cfcf_complete() {
  local cur prev words cword
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"

  # Embedded command tree. JSON-shaped: { children: [...], flags: [...] } per node.
  local tree='${tree}'

  # Walk the tree using jq-equivalent shell parsing. We do this in pure
  # bash to avoid a hard \`jq\` dep. The tree shape is shallow (4 levels
  # max: clio docs ingest --document-id), so we hand-walk it.
  local -a path=()
  local i=1
  while [ "$i" -lt "$COMP_CWORD" ]; do
    local w="\${COMP_WORDS[$i]}"
    case "$w" in
      -*) ;;  # skip flags when descending
      *) path+=("$w") ;;
    esac
    i=$((i+1))
  done

  # Resolve candidates by feeding tree + path into a small shell helper.
  local candidates
  candidates="$(_cfcf_candidates_at "$tree" "\${path[@]}")"
  COMPREPLY=( $(compgen -W "$candidates" -- "$cur") )
}

# Helper: prints space-separated candidates (subcommand names + long flags)
# for the given path through the tree.
_cfcf_candidates_at() {
  local tree="$1"; shift
  # Use python (preferred, ships with macOS + most Linux) or fall back
  # to a no-op. We avoid jq because installing jq for completion is a
  # poor-UX requirement.
  if command -v python3 >/dev/null 2>&1; then
    python3 - <<EOF "$tree" "$@"
import json, sys
tree = json.loads(sys.argv[1])
node = tree
for token in sys.argv[2:]:
    found = None
    for child in node.get("children", []):
        if child["name"] == token:
            found = child
            break
    if found is None:
        # Unknown token -- still useful to show all current children + flags.
        break
    node = found
names = [c["name"] for c in node.get("children", [])]
flags = node.get("flags", [])
print(" ".join(names + flags))
EOF
  fi
}

complete -F _cfcf_complete cfcf
`;
}

/**
 * Render a zsh completion script. zsh's compdef framework supports much
 * richer descriptions per candidate, but we keep it simple to mirror the
 * bash output -- one candidate set per node, no per-flag descriptions.
 * Future pass can pull commander's `.description()` per option to give
 * zsh users the richer form.
 */
export function renderZshCompletion(root: NodeInfo): string {
  const tree = JSON.stringify(serialiseForShell(root));
  return `#compdef cfcf
# zsh completion for cfcf -- generated by \`cfcf completion zsh\`
# Place this file in a directory on your $fpath, e.g.:
#   mkdir -p ~/.zsh/completions
#   cfcf completion zsh > ~/.zsh/completions/_cfcf
#   # then add this to your ~/.zshrc:
#   #   fpath=(~/.zsh/completions $fpath)
#   #   autoload -U compinit && compinit

_cfcf() {
  local tree='${tree}'
  local -a candidates
  local -a path
  local i

  # Collect path tokens before the cursor (skip flags).
  for ((i=2; i < CURRENT; i++)); do
    case "\${words[$i]}" in
      -*) ;;
      *) path+=("\${words[$i]}") ;;
    esac
  done

  if (( $+commands[python3] )); then
    candidates=( \${(f)"$(python3 - <<EOF "$tree" "\${path[@]}"
import json, sys
tree = json.loads(sys.argv[1])
node = tree
for token in sys.argv[2:]:
    found = None
    for child in node.get("children", []):
        if child["name"] == token:
            found = child
            break
    if found is None:
        break
    node = found
names = [c["name"] for c in node.get("children", [])]
flags = node.get("flags", [])
print("\\n".join(names + flags))
EOF
)"} )
    compadd -a candidates
  fi
}

compdef _cfcf cfcf
`;
}

/**
 * Trim the tree to the fields the shell scripts actually need.
 * (Currently identical to NodeInfo; kept as a separate function so we
 * can drop richer fields later without breaking the shell scripts.)
 */
function serialiseForShell(node: NodeInfo): NodeInfo {
  return {
    name: node.name,
    flags: node.flags,
    children: node.children.map(serialiseForShell),
  };
}

/**
 * Detect the user's shell from $SHELL. Returns "bash" | "zsh" | null.
 * Used by `cfcf completion install` to print the right instructions.
 */
function detectShell(): "bash" | "zsh" | null {
  const shell = process.env.SHELL ?? "";
  if (shell.endsWith("/zsh")) return "zsh";
  if (shell.endsWith("/bash")) return "bash";
  return null;
}

export function registerCompletionCommand(program: Command): void {
  // Top-level `cfcf completion` since shell completion is a cfcf-level
  // concern, not a Clio one. Lives alongside `init`, `status`, `doctor`.
  const completionCmd = program
    .command("completion")
    .description("Emit shell completion scripts (bash, zsh) for the cfcf CLI");

  completionCmd
    .command("bash")
    .description("Emit a bash completion script (redirect to a file + source it)")
    .action(() => {
      // We need access to the parent program to walk its tree. Commander
      // exposes the parent via `.parent`.
      const root = program;
      const tree = walkCommands(root);
      process.stdout.write(renderBashCompletion(tree));
    });

  completionCmd
    .command("zsh")
    .description("Emit a zsh completion script (place on your $fpath as _cfcf)")
    .action(() => {
      const root = program;
      const tree = walkCommands(root);
      process.stdout.write(renderZshCompletion(tree));
    });

  completionCmd
    .command("install")
    .description("Print shell-specific install instructions for tab completion")
    .action(() => {
      const detected = detectShell();
      console.log("cfcf shell completion -- install instructions");
      console.log();
      if (detected === "bash" || detected === null) {
        console.log("Bash:");
        console.log("  cfcf completion bash > ~/.cfcf-completion.bash");
        console.log("  echo 'source ~/.cfcf-completion.bash' >> ~/.bashrc");
        console.log("  # then open a new shell, or: source ~/.bashrc");
        console.log();
      }
      if (detected === "zsh" || detected === null) {
        console.log("Zsh:");
        console.log("  mkdir -p ~/.zsh/completions");
        console.log("  cfcf completion zsh > ~/.zsh/completions/_cfcf");
        console.log("  # add to ~/.zshrc if not already present:");
        console.log("  #   fpath=(~/.zsh/completions $fpath)");
        console.log("  #   autoload -U compinit && compinit");
        console.log();
      }
      if (detected) {
        console.log(`(Detected shell: ${detected}.)`);
      } else {
        console.log("(Couldn't detect your shell from $SHELL; both forms shown.)");
      }
      console.log();
      console.log("After re-sourcing, tab-complete works on every cfcf verb:");
      console.log("  cfcf <TAB>            → top-level commands");
      console.log("  cfcf clio <TAB>       → search audit reindex stats docs metadata projects embedder");
      console.log("  cfcf clio docs <TAB>  → list ingest get edit delete restore versions");
      console.log();
      console.log("Re-run `cfcf completion {bash,zsh}` after upgrading cfcf to pick up new verbs.");
    });
}
