/**
 * `cfcf help [topic]` -- print user-facing documentation from the bundled
 * help content (generated by scripts/embed-help-content.ts from
 * docs/guides/*.md + docs/api/server-api.md).
 *
 * Behaviour:
 *   cfcf help              -> terse hub (topic catalogue + tips). Default,
 *                              same shape as `git help`, `gh help`,
 *                              `kubectl help` -- a glanceable summary,
 *                              not a wall of Markdown.
 *   cfcf help <topic>      -> full content for that topic (slug or alias).
 *   cfcf help --full       -> full user manual (i.e. the old default).
 *   cfcf help --list       -> same as `cfcf help` with no arg (legacy).
 *
 * Output is plain Markdown. Pipe through a Markdown renderer for
 * prettified output:
 *
 *   cfcf help workflow | glow      # https://github.com/charmbracelet/glow
 *   cfcf help workflow | bat -l md
 *
 * Plan item 5.8 PR2/PR3 + UX revision (default-to-hub, 2026-04-27).
 */

import type { Command } from "commander";
import { listHelpTopics, resolveHelpTopic, getHelpContent } from "@cfcf/core";

/**
 * One-line summary per topic. Hand-curated so the hub reads like a
 * useful index rather than dumping each guide's full prose intro.
 * Keep these terse -- 60-90 chars each, fit on one terminal line at
 * 80 columns alongside the slug + title.
 */
const TOPIC_SUMMARIES: Record<string, string> = {
  manual:          "Concept primer + 3-min getting started + pointers to focused guides",
  workflow:        "Run a loop end-to-end: setup, Problem Pack, review, run, reflect",
  cli:             "Verb-by-verb CLI reference (server, workspace, run, clio, …)",
  clio:            "Cross-workspace memory: search, ingest, embedders, projects",
  installing:      "Install, upgrade, uninstall (curl, bun install -g, self-update)",
  troubleshooting: "Common issues + fixes; first stop after `cfcf doctor`",
  api:             "HTTP API reference (every server endpoint)",
};

/**
 * Render the hub: glanceable catalogue + drill-in tips. This is what
 * `cfcf help` (no arg) prints. Designed to fit on a single 80-column
 * terminal screen so the user can scan + pick a topic quickly.
 */
function fmtHub(): string {
  const rows: string[] = [];
  rows.push("cfcf -- Cerefox Code Factory (cf²)");
  rows.push("Deterministic orchestration harness for AI coding agents.");
  rows.push("");
  rows.push("Topics:");
  for (const t of listHelpTopics()) {
    const summary = TOPIC_SUMMARIES[t.slug] ?? t.title;
    rows.push(`  ${t.slug.padEnd(18)} ${summary}`);
  }
  rows.push("");
  rows.push("Drill in:");
  rows.push("  cfcf help <topic>      Print a specific topic in full");
  rows.push("  cfcf help --full       Print the user manual (long-form)");
  rows.push("  cfcf help --list       Same as `cfcf help` (legacy)");
  rows.push("");
  rows.push("Other entry points:");
  rows.push("  cfcf doctor            Self-check + common-issue diagnostics");
  rows.push("  cfcf <command> --help  Per-command flag reference");
  rows.push("");
  rows.push("Tip: pipe through a Markdown renderer for richer output:");
  rows.push("  cfcf help workflow | glow");
  rows.push("  cfcf help workflow | bat -l md");
  return rows.join("\n");
}

function printTopic(slug: string): void {
  const topic = resolveHelpTopic(slug);
  if (!topic) {
    console.error(`Unknown help topic: ${slug}\n`);
    console.error(fmtHub());
    process.exit(1);
  }
  const body = getHelpContent(topic.slug);
  if (body === null) {
    console.error(`Help topic "${topic.slug}" has no content (build artifact missing?). Run: bun run scripts/embed-help-content.ts`);
    process.exit(1);
  }
  process.stdout.write(body);
  if (!body.endsWith("\n")) process.stdout.write("\n");
  // Footer line points at the source on disk for users who want to edit
  // / contribute. Goes to stderr so it doesn't pollute pipes.
  process.stderr.write(`\n--- source: ${topic.source} -- contribute via the cfcf repo\n`);
}

export function registerHelpCommand(program: Command): void {
  program
    .command("help [topic]")
    .description("Print user-facing documentation. With no arg: glanceable topic hub.")
    .option("--list", "Show the topic hub (legacy alias of `cfcf help` no-arg)")
    .option("--full", "Print the user manual in full (long-form; ~280 lines)")
    .action((topic: string | undefined, opts: { list?: boolean; full?: boolean }) => {
      if (topic) {
        // Explicit topic always wins: `cfcf help cli` -> cli-usage.md.
        printTopic(topic);
        return;
      }
      if (opts.full) {
        printTopic("manual");
        return;
      }
      // Default + --list both land here: terse hub.
      console.log(fmtHub());
    });
}
