/**
 * `cfcf help [topic]` -- print user-facing documentation from the bundled
 * help content (generated by scripts/embed-help-content.ts from
 * docs/guides/*.md + docs/api/server-api.md).
 *
 * With no arg: prints the manual (or a topic list if --list is passed).
 * With an arg:  prints that topic, resolving slugs + aliases:
 *   cfcf help              -> manual
 *   cfcf help manual       -> manual.md
 *   cfcf help workflow     -> workflow.md
 *   cfcf help cli          -> cli-usage.md (alias)
 *   cfcf help clio         -> clio-quickstart.md
 *   cfcf help memory       -> clio-quickstart.md (alias)
 *   cfcf help install      -> installing.md (alias)
 *   cfcf help troubleshoot -> troubleshooting.md (alias)
 *   cfcf help api          -> server-api.md
 *
 * Output is plain Markdown by default (renders well in modern terminals
 * with rich text support; gracefully degrades to plain text everywhere
 * else). Pipe through a markdown renderer for prettified output:
 *
 *   cfcf help workflow | glow      # https://github.com/charmbracelet/glow
 *   cfcf help workflow | bat -l md
 *
 * Plan item 5.8 PR2/PR3.
 */

import type { Command } from "commander";
import { listHelpTopics, resolveHelpTopic, getHelpContent } from "@cfcf/core";

function fmtList(): string {
  const rows: string[] = [];
  rows.push("Available help topics:");
  rows.push("");
  for (const t of listHelpTopics()) {
    const aliasNote = t.aliases.length > 0 ? `  (also: ${t.aliases.join(", ")})` : "";
    rows.push(`  ${t.slug.padEnd(18)} ${t.title}${aliasNote}`);
  }
  rows.push("");
  rows.push("Usage:");
  rows.push("  cfcf help              -- print the user manual (default)");
  rows.push("  cfcf help <topic>      -- print a specific topic");
  rows.push("  cfcf help --list       -- show this list");
  rows.push("");
  rows.push("Tip: pipe through a Markdown renderer for richer output:");
  rows.push("  cfcf help workflow | glow");
  rows.push("  cfcf help workflow | bat -l md");
  return rows.join("\n");
}

function printTopic(slug: string): void {
  const topic = resolveHelpTopic(slug);
  if (!topic) {
    console.error(`Unknown help topic: ${slug}`);
    console.error(``);
    console.error(fmtList());
    process.exit(1);
  }
  const body = getHelpContent(topic.slug);
  if (body === null) {
    console.error(`Help topic "${topic.slug}" has no content (build artifact missing?). Run: bun run scripts/embed-help-content.ts`);
    process.exit(1);
  }
  process.stdout.write(body);
  if (!body.endsWith("\n")) process.stdout.write("\n");
  // Footer line points at the source on disk for users who want to edit
  // / contribute. Goes to stderr so it doesn't pollute pipes.
  process.stderr.write(`\n--- source: ${topic.source} -- contribute via the cfcf repo\n`);
}

export function registerHelpCommand(program: Command): void {
  program
    .command("help [topic]")
    .description("Print user-facing documentation. Default topic = manual.")
    .option("--list", "List available topics + their aliases")
    .action((topic: string | undefined, opts: { list?: boolean }) => {
      if (opts.list) {
        console.log(fmtList());
        return;
      }
      const slug = topic ?? "manual";
      printTopic(slug);
    });
}
