/**
 * Web asset loader.
 *
 * Prefers the embedded bundle generated by `scripts/embed-web-dist.ts`
 * (so the compiled binary is self-contained). Falls back to reading
 * from `packages/web/dist/` on disk for dev sessions where the
 * generated file hasn't been produced yet.
 */

import { readFile, stat } from "fs/promises";
import { join, dirname } from "path";

export interface LoadedAsset {
  contentType: string;
  body: Uint8Array;
}

// Dynamically import so a missing generated file doesn't break `bun run dev:server`.
// (The generated file is produced by `bun run build:web`.)
let embedded: Record<string, { contentType: string; body: Uint8Array }> | null = null;
let embeddedAttempted = false;

async function loadEmbedded(): Promise<typeof embedded> {
  if (embeddedAttempted) return embedded;
  embeddedAttempted = true;
  try {
    const mod = await import("./web-assets.generated.js");
    embedded = mod.WEB_ASSETS ?? null;
  } catch {
    embedded = null;
  }
  return embedded;
}

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".map": "application/json; charset=utf-8",
};

function contentTypeFor(p: string): string {
  const lower = p.toLowerCase();
  for (const [ext, ct] of Object.entries(CONTENT_TYPES)) {
    if (lower.endsWith(ext)) return ct;
  }
  return "application/octet-stream";
}

function getDevDistPath(): string {
  return join(dirname(new URL(import.meta.url).pathname), "..", "..", "web", "dist");
}

let devDistAvailable: boolean | null = null;
async function isDevDistAvailable(): Promise<boolean> {
  if (devDistAvailable !== null) return devDistAvailable;
  try {
    await stat(join(getDevDistPath(), "index.html"));
    devDistAvailable = true;
  } catch {
    devDistAvailable = false;
  }
  return devDistAvailable;
}

/**
 * Return true if any source of assets (embedded or dev dist) is available.
 * Used by the app router to decide whether to register the static routes.
 */
export async function hasWebAssets(): Promise<boolean> {
  const e = await loadEmbedded();
  if (e && Object.keys(e).length > 0) return true;
  return isDevDistAvailable();
}

/**
 * Load a single asset by request path (e.g. `/index.html`, `/assets/foo.js`).
 * Returns null if the asset does not exist.
 */
export async function loadAsset(path: string): Promise<LoadedAsset | null> {
  // Normalize and guard against path traversal
  const normalized = path.replace(/\/+/g, "/").replace(/\.\.(\/|$)/g, "");

  const e = await loadEmbedded();
  if (e && normalized in e) {
    return { contentType: e[normalized].contentType, body: e[normalized].body };
  }

  // Dev fallback: read from disk
  if (await isDevDistAvailable()) {
    const abs = join(getDevDistPath(), normalized);
    try {
      const bytes = await readFile(abs);
      return { contentType: contentTypeFor(normalized), body: new Uint8Array(bytes) };
    } catch {
      return null;
    }
  }

  return null;
}

/**
 * Return the index.html asset (the SPA entry point for any route).
 */
export async function loadIndex(): Promise<LoadedAsset | null> {
  return loadAsset("/index.html");
}

/**
 * Return whether the embedded bundle (not the dev fallback) is present.
 * Useful for reporting in `cfcf server status`.
 */
export async function embeddedBundlePresent(): Promise<boolean> {
  const e = await loadEmbedded();
  return !!(e && Object.keys(e).length > 0);
}
