#!/usr/bin/env bun
/**
 * Embed the built web GUI (`packages/web/dist/`) into a TypeScript module
 * that the server can import. This produces a self-contained asset bundle
 * that survives `bun build --compile` -- the compiled binary carries its
 * own copy of the web UI with no external files required at runtime.
 *
 * Input:  packages/web/dist/**
 * Output: packages/server/src/web-assets.generated.ts  (gitignored)
 *
 * The generated file exports a `WEB_ASSETS` map keyed by the request path
 * (e.g. "/index.html", "/assets/index-XXX.js") whose values are
 * `{ contentType, body }` entries with body stored as base64.
 *
 * This script runs as part of `bun run build:web`.
 */

import { readdir, readFile, writeFile, stat } from "fs/promises";
import { join, relative } from "path";

const WEB_DIST = join(import.meta.dir, "..", "packages", "web", "dist");
const OUT_FILE = join(import.meta.dir, "..", "packages", "server", "src", "web-assets.generated.ts");

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".map": "application/json; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
};

function contentTypeFor(name: string): string {
  const lower = name.toLowerCase();
  for (const [ext, ct] of Object.entries(CONTENT_TYPES)) {
    if (lower.endsWith(ext)) return ct;
  }
  return "application/octet-stream";
}

async function walk(dir: string): Promise<string[]> {
  const entries = await readdir(dir);
  const files: string[] = [];
  for (const e of entries) {
    const p = join(dir, e);
    const st = await stat(p);
    if (st.isDirectory()) {
      files.push(...(await walk(p)));
    } else {
      files.push(p);
    }
  }
  return files;
}

async function main() {
  try {
    await stat(WEB_DIST);
  } catch {
    console.error(`embed-web-dist: ${WEB_DIST} does not exist. Run \`bun run build:web\` first or ensure Vite has produced dist/.`);
    process.exit(1);
  }

  const files = await walk(WEB_DIST);
  if (files.length === 0) {
    console.error(`embed-web-dist: no files under ${WEB_DIST}`);
    process.exit(1);
  }

  const entries: { path: string; contentType: string; base64: string; size: number }[] = [];
  for (const f of files) {
    const rel = relative(WEB_DIST, f).replace(/\\/g, "/");
    const routePath = "/" + rel;
    const bytes = await readFile(f);
    entries.push({
      path: routePath,
      contentType: contentTypeFor(rel),
      base64: bytes.toString("base64"),
      size: bytes.byteLength,
    });
  }

  // Sort for deterministic output
  entries.sort((a, b) => a.path.localeCompare(b.path));

  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * Generated by scripts/embed-web-dist.ts -- do not edit by hand.`);
  lines.push(` * Regenerated every time \`bun run build:web\` is invoked.`);
  lines.push(` *`);
  lines.push(` * Embeds the built web GUI so the compiled binary is self-contained.`);
  lines.push(` * Total bundled size: ${entries.reduce((n, e) => n + e.size, 0)} bytes`);
  lines.push(` * Files: ${entries.length}`);
  lines.push(` */`);
  lines.push("");
  lines.push("export interface EmbeddedAsset {");
  lines.push("  contentType: string;");
  lines.push("  body: Uint8Array;");
  lines.push("}");
  lines.push("");
  lines.push("function fromBase64(s: string): Uint8Array {");
  lines.push("  // Bun and Node both expose atob; Buffer is faster but not always in browser lib types.");
  lines.push('  const bin = typeof Buffer !== "undefined" ? Buffer.from(s, "base64") : atob(s);');
  lines.push("  if (bin instanceof Uint8Array) return bin;");
  lines.push('  // atob path: bin is a binary string');
  lines.push("  const out = new Uint8Array((bin as string).length);");
  lines.push("  for (let i = 0; i < out.length; i++) out[i] = (bin as string).charCodeAt(i);");
  lines.push("  return out;");
  lines.push("}");
  lines.push("");
  lines.push("export const WEB_ASSETS: Record<string, EmbeddedAsset> = {");
  for (const e of entries) {
    lines.push(`  ${JSON.stringify(e.path)}: { contentType: ${JSON.stringify(e.contentType)}, body: fromBase64(${JSON.stringify(e.base64)}) },`);
  }
  lines.push("};");
  lines.push("");
  lines.push("export const WEB_ASSETS_PRESENT = true;");
  lines.push("");

  await writeFile(OUT_FILE, lines.join("\n"), "utf-8");

  const total = entries.reduce((n, e) => n + e.size, 0);
  console.log(`embed-web-dist: wrote ${OUT_FILE}`);
  console.log(`  ${entries.length} files, ${(total / 1024).toFixed(1)} KiB`);
}

main().catch((err) => {
  console.error("embed-web-dist failed:", err);
  process.exit(1);
});
