#!/usr/bin/env bun
/**
 * Embed the user-facing guides (`docs/guides/*.md` + selected friends)
 * into a TypeScript module that both the CLI (`cfcf help <topic>`) and
 * the server (`/api/help/*`, web UI Help tab) can import. Same shape as
 * `scripts/embed-web-dist.ts`: a generated module that survives
 * `bun build --compile` without external files at runtime.
 *
 * Input:  docs/guides/*.md (+ selected docs/api/*.md)
 * Output: packages/core/src/help-content.generated.ts (gitignored)
 *
 * The generated file exports a `HELP_TOPICS` map keyed by topic slug.
 * Each entry has `{ slug, title, source, content }`:
 *   - slug:    cli-friendly name (e.g. "manual", "workflow", "clio")
 *   - title:   human-readable title parsed from the first H1 in the file
 *   - source:  original file path (for the "view source" footer)
 *   - content: full Markdown body
 *
 * This script runs as part of `bun run build:cli` (and is wired into
 * `scripts/build-cli.sh` so release tarballs ship with the latest docs).
 *
 * Source-of-truth principle: the canonical doc files live in
 * `docs/guides/`. This generator reads them at build time. After install,
 * there's no separate "shipped docs" location to keep in sync -- the
 * generated module IS the shipped form.
 */

import { readFile, writeFile, stat } from "fs/promises";
import { join, basename, relative } from "path";

const REPO_ROOT = join(import.meta.dir, "..");
const OUT_FILE = join(REPO_ROOT, "packages", "core", "src", "help-content.generated.ts");

/**
 * Topics to embed, in display order. Each entry maps to one Markdown
 * file. The slug is what `cfcf help <slug>` accepts; the source is the
 * canonical path. Adding a new topic = add a row + a Markdown file.
 *
 * `manual` is intentionally first -- `cfcf help` with no argument
 * defaults to it.
 */
const TOPICS: Array<{ slug: string; source: string; aliases?: string[] }> = [
  { slug: "manual",          source: "docs/guides/manual.md" },
  { slug: "workflow",        source: "docs/guides/workflow.md" },
  { slug: "cli",             source: "docs/guides/cli-usage.md", aliases: ["cli-usage", "commands"] },
  { slug: "clio",            source: "docs/guides/clio-quickstart.md", aliases: ["memory"] },
  { slug: "spec",            source: "docs/guides/product-architect.md", aliases: ["pa", "product-architect"] },
  { slug: "installing",      source: "docs/guides/installing.md", aliases: ["install"] },
  { slug: "troubleshooting", source: "docs/guides/troubleshooting.md", aliases: ["troubleshoot"] },
  { slug: "api",             source: "docs/api/server-api.md" },
];

interface ParsedTopic {
  slug: string;
  title: string;
  source: string;
  content: string;
  aliases: string[];
}

/** Pull the H1 title from the first `# ` line; fall back to the slug. */
function extractTitle(slug: string, content: string): string {
  const m = content.match(/^#\s+(.+)$/m);
  if (m) return m[1].trim();
  return slug;
}

async function loadTopic(t: { slug: string; source: string; aliases?: string[] }): Promise<ParsedTopic | null> {
  const path = join(REPO_ROOT, t.source);
  try {
    await stat(path);
  } catch {
    console.warn(`[embed-help] WARN: topic "${t.slug}" missing source ${t.source}; skipping`);
    return null;
  }
  const content = await readFile(path, "utf-8");
  return {
    slug: t.slug,
    title: extractTitle(t.slug, content),
    source: t.source,
    content,
    aliases: t.aliases ?? [],
  };
}

/**
 * Markdown content can include backticks, dollar signs, and template-
 * literal close sequences. Use String.raw + base64 to side-step every
 * escaping concern; the generated module decodes once at module load
 * and the cost is negligible (~700 KB across all topics).
 */
function asBase64Literal(content: string): string {
  return Buffer.from(content, "utf-8").toString("base64");
}

async function main() {
  const topics: ParsedTopic[] = [];
  for (const t of TOPICS) {
    const loaded = await loadTopic(t);
    if (loaded) topics.push(loaded);
  }
  if (topics.length === 0) {
    console.error("[embed-help] ERROR: no topics loaded; aborting");
    process.exit(1);
  }

  // Build slug + alias index entries.
  const entries: string[] = [];
  for (const t of topics) {
    const aliasList = t.aliases.length > 0
      ? `[${t.aliases.map((a) => JSON.stringify(a)).join(", ")}]`
      : "[]";
    entries.push(
      `  ${JSON.stringify(t.slug)}: { slug: ${JSON.stringify(t.slug)}, title: ${JSON.stringify(t.title)}, source: ${JSON.stringify(t.source)}, aliases: ${aliasList}, contentBase64: ${JSON.stringify(asBase64Literal(t.content))} },`,
    );
  }

  const generated = `/* eslint-disable */
// AUTO-GENERATED by scripts/embed-help-content.ts. DO NOT EDIT BY HAND.
// Re-generate via \`bun run scripts/embed-help-content.ts\` (also runs as
// part of \`bun run build\` and \`scripts/build-cli.sh\`).
//
// Source files live in docs/guides/ + docs/api/. Updates flow through
// the generator, not by editing this file.

export interface HelpTopic {
  /** CLI-friendly slug (e.g. "manual", "workflow"). */
  slug: string;
  /** Human-readable title parsed from the first H1. */
  title: string;
  /** Original source path (for "view source" footers). */
  source: string;
  /** Alternate slugs the CLI accepts (e.g. "cli" / "cli-usage" / "commands"). */
  aliases: string[];
  /** Full Markdown content, base64-encoded for safe round-trip through TS. */
  contentBase64: string;
}

export const HELP_TOPICS: Record<string, HelpTopic> = {
${entries.join("\n")}
};

/** Decode a topic's Markdown body. Cached after first decode. */
const _decodeCache: Record<string, string> = {};
export function getHelpContent(slug: string): string | null {
  const t = HELP_TOPICS[slug];
  if (!t) return null;
  if (_decodeCache[slug] === undefined) {
    _decodeCache[slug] = Buffer.from(t.contentBase64, "base64").toString("utf-8");
  }
  return _decodeCache[slug];
}

/** Resolve a user-supplied topic name -- canonical slug or alias -- to a HelpTopic. */
export function resolveHelpTopic(query: string): HelpTopic | null {
  const q = query.trim().toLowerCase();
  if (HELP_TOPICS[q]) return HELP_TOPICS[q];
  for (const t of Object.values(HELP_TOPICS)) {
    if (t.aliases.includes(q)) return t;
  }
  return null;
}

/** All topics, in declaration order (driven by TOPICS in the generator). */
export function listHelpTopics(): HelpTopic[] {
  return Object.values(HELP_TOPICS);
}
`;

  await writeFile(OUT_FILE, generated, "utf-8");
  const totalChars = topics.reduce((sum, t) => sum + t.content.length, 0);
  console.log(`[embed-help] embedded ${topics.length} topics (${totalChars.toLocaleString()} chars total)`);
  for (const t of topics) {
    console.log(`  ${t.slug.padEnd(18)} ${t.content.length.toString().padStart(7)} chars   ${relative(REPO_ROOT, join(REPO_ROOT, t.source))}`);
  }
  console.log(`  -> ${relative(REPO_ROOT, OUT_FILE)}`);
}

main().catch((err) => {
  console.error("[embed-help] FAILED:", err);
  process.exit(1);
});
